### PR TITLE
Add directory to PHPCS

### PR DESCRIPTION
**Pull request by szepeviktor**
:)

### CODE REVIEW

**Comment by szepeviktor** [comment]
Now PHPCS is running 🍏 I suggest you to follow PSR-12

**Comment by widoz** [comment]
Uh, I missed the php config file. I usually follow `inpsyde/php-coding-standards` but recently I found my self want to have something more simple with less restrictions and checks agains things which are not coding style into separated tools.

Do you have a suggestion for a possible configuration?

**Comment by szepeviktor** [comment]
🔫 This is my super-duper laser cannon: https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset

**Comment by widoz** [comment]
I thought to step away from WordPress coding styles, otherwise I would continue with `inpsyde/php-coding-standards`.

**Comment by szepeviktor** [comment]
The trick is: my ruleset does **not** include [the spacing/indentation/upper-lowercasing part of WPCS](https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset/blob/master/PSR12NeutronRuleset/ruleset.xml#L65-L83), only its benefits!

**Comment by widoz** [comment]
I'll take it into account thanks. 
Right know I haven't decided even though I'm inclined to just use `PSR12` as it is and nothing else but I have to admit I need more time to make research and decide the boundaries of what consider coding standard and what start to be a code analysis tool.

**Comment by szepeviktor** [comment]
Old horses don't learn new tricks.
https://github.com/widoz/event-listeners-collection/commit/9407953d746ad35a608fb2f0a833fb006eb03f50

I am a TravisCI Advocate.

**Pull request closed without merging**
